### ISSUE TITLE
problems about running

### ISSUE THREAD

**Issue by flighted** [adelbibi/Target-Response-Adaptation-for-Correlation-Filter-Tracking#1]
Hello!
      when I run the code of this paper ,it always shows "Not enough input arguments".I am confused about it   and  'scale_step'.So I write here for help. I would appreciate it if you could answer my question.

**Comment by adelbibi** [comment]
Hello,

Hope all is well.

Are you running the tracker through the OTB benchmark evaluation code?
*https://sites.google.com/site/trackerbenchmark/benchmarks/v10*
 Once you do, navigate to "\tracker_benchmark\trackers" directory. Create a new file and paste all the contents of this repo there. Once you do, navigate to "\tracker_benchmark\util" and open up the "configTrackers.m" file and add the the following there:

SMAF_AT =  struct('name','SAMF_AT','namePaper','SAMF_AT')
trackers = SMAF_AT;

Let me know if you have any further issues.

Best,
Bibi

**Comment by flighted** [comment]
Hello!
         Thank you for your reply. Firstly,I did as it notes.I done what you said,But there are some errors I don't understand.When I run _SAMF_at,it always errors  at 'seq = evalin('base', 'subs');' when I run _SAMF, it always error at  163  fprintf(' Scale Step ................ %u\n', scale_step); I search the internet,but I have no idea.
         I am sorry requesting you again!I would appreciate it if you could answer my question.Thanks!

**Comment by adelbibi** [comment]
Hello,

No worries at all.
Oh, don't run (run_SAMF_AT.m). Once you move the files in the tracker directory. Go back to the top directory (\tracker_benchmark) and run (main_running_OPE.m)

Please let me know if that worked.

Best,

**Comment by flighted** [comment]
Hello,
I apologize for replying so late。I try it as you say in benchmark,I can get theTRE and SRE.When I run OPE,it
don't work.I think I  did wrong in some detail.I will try again.Thank you for your answer.

**Comment by adelbibi** [comment]
Hello,

No need to apologize. If you are still facing a difficulty, we can skype and resolve your issue.
Send me your skype handle where later we can arrange for a time that suits both of us.

Best,
